### PR TITLE
PR Template Revisions

### PR DESCRIPTION
**Pull request by hpoom**
I have made some changes to the PR to make it more in line with how I think it should be.

My work is heavily based off of [this blog](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/) post and [this PR Template](https://github.com/sprintly/sprint.ly-culture/blob/master/pr-template.md).

### CODE REVIEW

**Comment by robhuzzey** [comment]
+1

**Comment by lukefrake** [comment]
Are we purposely ignoring thing like 'have you cross browser tested this?'

Things like 'does this require a blog post' Are nice but think we are missing some core stuff?

+1 to everything that's in here but just think it needs more. Don't mind putting another PR for the bis I mean. Just want to understand if we are avoiding them on purpose?

**Comment by hpoom** [comment]
Not ignoring x-browser testing on purpose, just forgot it.

If you agree with what I have put then +1 and I will merge. Any additions you can PR yourself. If on the other hand you disagree with any of the items I added, reject it.

I like the format or wordy replies followed by a checklist, but interested to see what others think.

**Comment by lukefrake** [comment]
Okay that's cool, ta for clearin that up.

Only things from me:

'(Any change to ways of working or interfaces needs a doc update)' - we've been working where every change is a change log and version bump so don't think this is needed.

'Will this feature require a new piece of infrastructure be implemented?' - I don't understand this one.

**Comment by hpoom** [comment]
OK I will remove explanation about doc.

Infrastructure question, is about does your PR require to role new hardware/servers. Does it needs cloud boxes.

**Comment by lukefrake** [comment]
Not sure infrastructure changes make sense in the PR. Only because i can't see it being used often then sounds like bloat. Would be interested to see others opinions though.

Other than that, +1 from me.

**Comment by hpoom** [comment]
OK merging now. @lukefrake do a PR for any x-browser stuff you think should be in there, or anything else I am missing out.

If others don't like the infrastructure question they can take it out and PR :smile:

**Pull request merged**
