### PR TITLE
Added a basic PR checklist

### PR DESCRIPTION
**Pull request by robhuzzey**
Hey all,

I've added the beginnings of what I believe our pull request should look like.

It's a little less traditional deliberately, I wanted to capture something different, let me know what you think.

### CODE REVIEW

**Comment by notABluesSinger** [comment]
Rather than bullets you can use [] for checkboxes; https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

**Comment by lukefrake** [comment]
I think there needs to be a bit more, personally.

I think there should be two parts, 1 part for the reviewer and 1 for the author.

The bits for the Author should be around explaining what this PR does, like what core have done [here](https://github.com/holidayextras/hx-culture/blob/master/pr-template.mkd#what-does-this-pr-do).

To be honest, I actually really like cores PR template, I think it has a lot of what we need in it, main points I like are

Author:
* I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
* I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
* I've tested this on...

Reviewer:
* I’ve run all the tests locally and they pass.
* I've checked this work against the requirements of the Jira.

Actually, I pretty much like all of what they have got... maybe we just use that?

**Comment by robhuzzey** [comment]
I deliberately didn't want to be too granular with the checklist. I wanted it to be more of a loose guide as we already have code review templates & I'm sure we'd have more granular things like that in time too.

**Comment by lukefrake** [comment]
Yeah, I think it shouldn't be more granular, but saying that I quite like the way core put there PR's together and use the checklist as the description for the request. See [here](https://github.com/holidayextras/hapi/pull/43)

**Comment by hpoom** [comment]
I am not a fan of Distributions. It is too long. It is a box ticking exercise. But I also this the one on the PR is too little. Look at these examples

https://github.com/sprintly/sprint.ly-culture/blob/master/pr-template.md

**Comment by hpoom** [comment]
https://quickleft.com/blog/pull-request-templates-make-code-review-easier/

**Comment by robhuzzey** [comment]
I just found this article on code review template:
http://blog.fogcreek.com/increase-defect-detection-with-our-code-review-checklist-example/

**Pull request merged**
