### PR TITLE
promises and indents

### PR DESCRIPTION
**Pull request by kevinhodges**
thoughts please

### CODE REVIEW

**Comment by lukefrake** [comment]
I'm a bit torn on this

I like the fact that you can see what is related to the first function, and I think multiple promises look neat.

But, I dislike the brackets don't line up and although I think it looks good when you have multiple, I think a Larry promise looks a bit strange.

```
function1()
  .then( function() {
  } );
```

**Comment by notABluesSinger** [comment]
Personally, I think the preceding dot tells you that it is part of a chain and therefore the indentation is surplus.
Indentation tells you that it is inside of a closure.

Also, I think all promises should now be called 'Larry' as per @lukefrake's suggestion :)

**Comment by kevinhodges** [comment]
The Q readme doesn't indent https://github.com/kriskowal/q
But the Strongloop stuff does http://strongloop.com/strongblog/promises-in-node-js-with-q-an-alternative-to-callbacks/

If that helps at all :)

**Comment by t1gr0u** [comment]
yep go for it

**Comment by hpoom** [comment]
I prefer the stongloop style. I think indent. Regards open close braces our editors show us those paired together and with the collapse in sidebar it is easy to see the blocks.

So I am :+1: on indent

**Comment by philmeehan** [comment]
I prefer indentation for readability

**Comment by robhuzzey** [comment]
I'm happy either way... :)

Rob Huzzey
Web Developer
robert.huzzey@holidayextras.com <nicki.lever@holidayextras.com>
*+44 (0) 1303 816332 **ext 3617*

 <https://twitter.com/theHuzz>  <http://uk.linkedin.com/in/roberthuzzey>
<http://about.me/robhuzzey>  <https://www.facebook.com/robhuzzey>
<https://plus.google.com/u/0/108907249903842573769/posts>

*Shortbreaks & New Ventures Team  *

*Holiday Extras Limited, Newingreen, Hythe, Kent CT21 4JF, United Kingdom.
Registered in England and Wales No 1693250 *


* This email is intended for the named addressee only. It may contain
confidential information. If you have received this message in error,
please let us know and then delete it from your system. You should not copy
the message, use it for any purpose nor disclose its contents to anyone.*

**Pull request merged**
