### PR TITLE
Remove 'How should developer review'

### PR DESCRIPTION
**Pull request by lukefrake**
This field always has 'visually' or 'eyes' written in it.

We can put any information into 'background context' if needed. So, lets remove it!

- [ ] I like this
- [ ] I also like this
- [x] I like cake

### CODE REVIEW

**Comment by notABluesSinger** [comment]
:+1:

**Comment by philmeehan** [comment]
It doesn't always have eyes on it so :-1:

**Comment by lukefrake** [comment]
@philmeehan - Do you think it has enough difference to 'background context' to be required?

**Comment by philmeehan** [comment]
I think so - sometimes we do ask for some specific things in that section.

**Pull request closed without merging**
